-- CREATE TABLE TOP_GAINERS FROM SCRACTH ON STARTUP
DROP TABLE IF EXISTS top_gainers;
CREATE TABLE top_gainers (id BIGINT AUTO_INCREMENT PRIMARY KEY, ticker VARCHAR(10), price DECIMAL(10,2), change_amount DECIMAL(10,2), change_percentage DECIMAL(5,2));

-- CREATE TABLE TOP_LOSERS FROM SCRACTH ON STARTUP
DROP TABLE IF EXISTS top_losers;
CREATE TABLE top_losers (id BIGINT AUTO_INCREMENT PRIMARY KEY, ticker VARCHAR(10), price DECIMAL(10,2), change_amount DECIMAL(10,2), change_percentage DECIMAL(5,2));